Added some simple (ANSI.SYS compatible) cursor movements:
bramus/ansi-php pull request #6
Opened 2021-08-30 13:40 UTC by nahkampf

- CUU - Up
- CUD - Down
- CUF - Forward
- CUB - Back
- CUP - Move to position (x,y)

2021-10-21 07:29 UTC, bramus requested changes
Hi @nahkampf, thanks for these additions.

Could you tweak the PR more, and

- [ ] Provide update PHPDoc comments? They don't match the contents of the functions _(I've marked only a few)_
- [ ] Fix the wrong call to `cuu` (which should be `cup`)

Thanks.

2021-10-21 07:29 UTC, bramus commented on src/Traits/EscapeSequences/CUP.php
> +        return $this->cuu($coords);
This should be `$this->cup`, no?

2021-10-21 07:29 UTC, bramus commented on src/Traits/EscapeSequences/CUU.php
> +     * Erase the entire current line.
This comment is not up-to-date

2021-10-21 07:29 UTC, bramus commented on src/Traits/EscapeSequences/CUP.php
> +     * Erase the entire current line.
This comment is not up-to-date

2021-10-21 07:29 UTC, bramus commented on src/Traits/EscapeSequences/CUP.php
> +     * @param  array $parameterByte Parameter byte to the CUP Escape Code
This comment is not up-to-date

2021-10-21 07:29 UTC, bramus commented on src/ControlSequences/EscapeSequences/CUU.php
> +     * SGR - SELECT GRAPHIC RENDITION
This comment is not up-to-date

2021-10-22 08:44 UTC, nahkampf commented
Sorry @bramus , that was a sloppy PR, has been fixed now!

2021-10-22 09:04 UTC, bramus approved these changes

2021-10-22 09:05 UTC, bramus commented
Thanks for updating the PR this fast, @nahkampf.

Will take a look some time next week to merge and provide an updated README + extra tests.

2021-10-27 22:41 UTC, bramus commented
I've reworked/fixed a few things:

- Reshuffle some code parts
- Rename arguments
- Fix comments
- Fix default values

And also made these additions:

- Added tests
- Updated README

Changes can be found at https://github.com/bramus/ansi-php/tree/feature-cursor. What do you think?

While I was at it, I create a small demo that leverages CUB (and EL): a little ascii-spinner:

![php-ascii-spinner](https://user-images.githubusercontent.com/213073/139157531-edacc91d-c48e-4ac7-a1c3-673c9a54b54f.gif)

The code for the spinner is included in the README.

2021-10-27 22:49 UTC, nahkampf commented
> I've reworked/fixed a few things:

That's pretty hot! I'm thinking of implementing cursor movements and save/restore screen to build fixed width/length input fields for a thing, I'll let you know if I get it working like I want it and I could post a gist or something. 👍

2021-10-28 10:38 UTC, bramus commented
> I'm thinking of implementing cursor movements and save/restore screen to build fixed width/length input fields for a thing, I'll let you know if I get it working like I want it and I could post a gist or something. 👍

Cool. I'll go ahead and merge my adjusted branch so that you can build further upon it.

2021-10-28 10:42 UTC, merged